In [8]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import pandas as pd

device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


In [13]:
from PIL import Image
import numpy as np

img = Image.open("./dataset/0/train_30_00000.png")
bitmap = np.array(img)

print(bitmap.shape)
print(bitmap)

(128, 128, 3)
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [20]:
data = []

base_dir = "./dataset"

for label in os.listdir(base_dir):
    label_path = os.path.join(base_dir, label)
    
    if os.path.isdir(label_path):
        for file in os.listdir(label_path):
            file_path = os.path.join(label_path, file)
            
            data.append({
                "filepath": file_path,
                "label": label
            })

df = pd.DataFrame(data)

print(df.iloc[0], df.iloc[10001], df.iloc[20001])

filepath    ./dataset\0\train_30_00000.png
label                                    0
Name: 0, dtype: object filepath    ./dataset\1\train_31_00019.png
label                                    1
Name: 10001, dtype: object filepath    ./dataset\2\train_32_00008.png
label                                    2
Name: 20001, dtype: object


In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits